### ISSUE TITLE
怎么不自动更新壁纸

### ISSUE THREAD

**Issue by crazyair** [YouthLin/BingWallpaper#2]
我什么权限都给了，华为手机

**Comment by youthlin** [comment]
您好。
1. 可能是必应服务器暂时连接不上，可以试试浏览器打开 cn.bing.com 排除这个可能性。
2.  自动更新壁纸依赖于自动启动功能，请检查是否通过第三方软件禁止自启了。
3. 尝试重装软件。（前两天我开机时还是可以用的）
